
run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - misspell
    - typecheck
    - bodyclose

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
    - path: cmd/
      linters:
        - gochecknoinits
